FROM ubuntu:16.04

# chrony and its dependencies
RUN apt-get update && apt-get install -y \
    man \
    chrony \
    adjtimex \
    && rm -rf /var/lib/apt/lists/*

# common dev tools
RUN apt-get update && apt-get install -y \
    nano \
    && rm -rf /var/lib/apt/lists/*

# config
COPY chrony.google-client.conf /etc/chrony/chrony.conf
